version: "3.7"

services:
  postgres:
    image: postgres
    container_name: testecontele_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: contele_app
    build: .
    command: ["./entrypoints.sh", "--", "npm", "start"]
    restart: always
    environment:
      DB_HOST: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  postgres: